//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "meters")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub number: i32,
    pub installation_date: DateTime,
    pub removal_date: DateTime,
    pub meter_type_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::meter_entries::Entity")]
    MeterEntries,
    #[sea_orm(
        belongs_to = "super::meter_types::Entity",
        from = "Column::MeterTypeId",
        to = "super::meter_types::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MeterTypes,
}

impl Related<super::meter_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MeterEntries.def()
    }
}

impl Related<super::meter_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MeterTypes.def()
    }
}
